version: '3.7'
name: fnc
services:
  pg:
    image: bitnami/postgresql:13.16.0
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=fnc